# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box
  config.vm.box = "trusty64-rails"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/763727/Boxes/rubyOnRails.box"

  # IP configuration
  config.vm.network :private_network, ip: "192.168.56.101"
  config.ssh.forward_agent = true

  # Project folder
  config.vm.synced_folder "./project", "~/project", id: "rails-project"

  # VirtualBox configuration
  config.vm.provider :virtualbox do |vb|
    # RAM - 512MB
    vb.customize ["modifyvm", :id, "--memory", "512"]
    # Name
    vb.customize ["modifyvm", :id, "--name", "trusty64-rails"]
  end
end
