# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box
  config.vm.box = "precise32-ruby"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/763727/precise32-ruby.box"

  # IP configuration
  config.vm.network :private_network, ip: "192.168.56.101"
  config.ssh.forward_agent = true

  # VirtualBox configuration
  config.vm.provider :virtualbox do |vb|
    # RAM - 2048MB
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    # Name
    vb.customize ["modifyvm", :id, "--name", "vagrant-ruby"]
  end
end
