# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box
  config.vm.box = "precise32-php"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/763727/precise32-php.box"
  
  # IP configuration
  config.vm.network :private_network, ip: "192.168.56.101"
  config.ssh.forward_agent = true

  # Www folder
  config.vm.synced_folder "./Projects", "/var/www", id: "php-projects"

  # VirtualBox configuration
  config.vm.provider :virtualbox do |vb|
    # RAM - 2048MB
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    # Name
    vb.customize ["modifyvm", :id, "--name", "vagrant-php"]
  end
end
